version: '2'
services:
    contacts2-app:
        image: contacts2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://contacts2-mysql:3306/contacts2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    contacts2-mysql:
        extends:
            file: mysql.yml
            service: contacts2-mysql
